Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -15,8 +15,8 @@ dos2unix skintool || { echo "Failed to convert script. Exiting..."; exit 1; }
 echo "[*] Making script executable..."
 chmod +x skintool || { echo "Failed to make script executable. Exiting..."; exit 1; }
 
-# Create symbolic link
+# Create symbolic link for 'skintool'
 echo "[*] Creating symbolic link..."
-ln -sf "$(pwd)/dark" /data/data/com.termux/files/usr/bin/dark || { echo "Failed to create symbolic link. Exiting..."; exit 1; }
+ln -sf "$(pwd)/skintool" /data/data/com.termux/files/usr/bin/dark || { echo "Failed to create symbolic link. Exiting..."; exit 1; }
 
 echo "[✔] Setup complete! You can now execute the tool by typing 'dark'."
