Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,16 +1,7 @@
 #!/bin/bash
 
-# Update and install required packages
-echo "[*] Updating and installing necessary packages..."
-pkg update -y && pkg upgrade -y
-pkg install git python python3 dos2unix curl -y
-
-# Clone the repository
-echo "[*] Cloning repository..."
-git clone https://github.com/darksideyt762/sidedark.git || { echo "Failed to clone the repository. Exiting..."; exit 1; }
-
-# Navigate to the repository directory
-cd sidedark || { echo "Repository directory not found. Exiting..."; exit 1; }
+# Navigate to the current directory
+cd "$(dirname "$0")" || { echo "Failed to navigate to script directory. Exiting..."; exit 1; }
 
 # Download items_index.txt
 echo "[*] Downloading Items_Index.txt..."
@@ -26,6 +17,6 @@ chmod +x skin || { echo "Failed to make script executable. Exiting..."; exit 1; 
 
 # Create symbolic link
 echo "[*] Creating symbolic link..."
-ln -sf $(pwd)/skin /data/data/com.termux/files/usr/bin/skin || { echo "Failed to create symbolic link. Exiting..."; exit 1; }
+ln -sf "$(pwd)/skin" /data/data/com.termux/files/usr/bin/skin || { echo "Failed to create symbolic link. Exiting..."; exit 1; }
 
 echo "[✔] Setup complete! You can now execute the tool by typing 'skin'."
